site_name: Substrate Docs
site_dir: ../docs
markdown_extensions:
  - attr_list
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: purple
nav:
  - Home: index.md
  - Attributes:
      - Notify: notify.md
      - Dependency Property: dependency-property.md