site_name: Substrate Docs
site_dir: ../docs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: purple
nav:
  - Home: index.md
  - Features: features.md
  - Attributes:
      - Notify: notify.md
      - Dependency Property: dependency-property.md
      - Theme: theme.md
      - IconPack: icons.md
      - Fonts: fonts.md
  
site_description: Automating the boring parts of WPF development.
repo_url: https://github.com/rharrison891/Substrate
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rharrison891/Substrate
copyright: >
  © 2025 Substrate — Built with ❤️ and MkDocs.