site_name: Substrate Docs
site_dir: ../docs
theme:
  name: material
nav:
  - Home: index.md
  - Landing: landing.md
  - Attributes:
      - Notify: notify.md
      - Dependency Property: dependency-property.md